from pydoc import describe
from django.db.models.signals import post_save, post_delete
from .models import Task
from django.dispatch import receiver

@receiver(post_save, sender=Task)
def autoGenerateDailyTask(sender,instance,created,**kwargs):
    print("Signal Fire Automatic")
    if created:
        Task = instance
        Task.objects.create(
            name=Task.name,
            description = Task.description
        )
        print("Task created")
        
@receiver(post_delete,sender=Task)     
def autoDailyTaskGone(sender, instance,**kwargs):
    data= instance
    print(instance.name)
    print(instance.description)
    print(instance.start_date)
    print(instance.end_date)
    fetchdata = Task.objects.get(name=data.name)
    data.delete()
    print("Post delete signal Called")
    


 

    

